fn main() {
    use std::io::Write;
    use std::path::Path;

    fn gen_pthread_mutex(out_file: &str) -> std::io::Result<()> {
        let mut output = Vec::new();
        writeln!(
            output,
            "// Generated by arceos_posix_api/build.rs — DO NOT edit!"
        )?;
        writeln!(
            output,
            r#"
typedef struct {{
    unsigned long long __l[5];
}} pthread_mutex_t;

#define PTHREAD_MUTEX_INITIALIZER {{ .__l = {{0, 0, 0, 0, 0}} }}
"#
        )?;
        std::fs::write(out_file, output)?;
        Ok(())
    }

    fn gen_c_to_rust_bindings(in_file: &str, out_file: &Path, checked_in: &Path) {
        println!("cargo:rerun-if-changed={in_file}");
        println!("cargo:rerun-if-changed={}", checked_in.display());

        let allow_types = [
            "stat",
            "size_t",
            "ssize_t",
            "off_t",
            "mode_t",
            "sock.*",
            "fd_set",
            "timeval",
            "pthread_t",
            "pthread_attr_t",
            "pthread_mutex_t",
            "pthread_mutexattr_t",
            "epoll_event",
            "iovec",
            "clockid_t",
            "rlimit",
            "aibuf",
        ];

        let allow_vars = [
            "CLOCK_.*",
            "O_.*",
            "AF_.*",
            "SOCK_.*",
            "IPPROTO_.*",
            "FD_.*",
            "F_.*",
            "_SC_.*",
            "EPOLL_CTL_.*",
            "EPOLL.*",
            "RLIMIT_.*",
            "EAI_.*",
            "MAXADDRS",
        ];

        #[derive(Debug)]
        struct MyCallbacks;

        impl bindgen::callbacks::ParseCallbacks for MyCallbacks {
            fn include_file(&self, fname: &str) {
                if !fname.contains("ax_pthread_mutex.h") {
                    println!("cargo:rerun-if-changed={fname}");
                }
            }
        }

        let target = std::env::var("TARGET").unwrap();
        let target_arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();

        // Some evaluator environments still ship libclang versions that do not
        // know the LoongArch target triple. Copy the checked-in fallback into
        // OUT_DIR instead of ever rewriting a tracked source file.
        if target_arch == "loongarch64" {
            std::fs::copy(checked_in, out_file).unwrap_or_else(|err| {
                panic!(
                    "cannot copy checked-in {} to {} for {target}: {err}",
                    checked_in.display(),
                    out_file.display()
                )
            });
            println!(
                "cargo:warning=using checked-in {}; libclang may not support target {target}",
                checked_in.display()
            );
            return;
        }

        let mut builder = bindgen::Builder::default()
            .header(in_file)
            .clang_arg("-I./../../ulib/axlibc/include")
            .parse_callbacks(Box::new(MyCallbacks))
            .derive_default(true)
            .size_t_is_usize(false)
            .use_core();

        // Remove the "-softfloat" suffix for some targets.
        if let Some(llvm_target) = target.strip_suffix("-softfloat") {
            builder = builder.clang_arg(format!("--target={llvm_target}"));
        }

        for ty in allow_types {
            builder = builder.allowlist_type(ty);
        }

        for var in allow_vars {
            builder = builder.allowlist_var(var);
        }

        builder
            .generate()
            .expect("Unable to generate C→Rust bindings")
            .write_to_file(out_file)
            .expect("Couldn't write bindings!");
    }

    gen_pthread_mutex("../../ulib/axlibc/include/ax_pthread_mutex.h").unwrap();
    let out_dir = std::path::PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));
    gen_c_to_rust_bindings(
        "ctypes.h",
        &out_dir.join("ctypes_gen.rs"),
        Path::new("src/ctypes_gen.rs"),
    );
}
